"""
This type stub file was generated by pyright.
"""

"""
Mostly irrelevant, but useful utilities common to UNIX and Windows.

Copyright (c) 2018 Gerard Marull-Paretas <gerard@teslabs.com>
Copyright (c) 2014 Mark Harviston <mark.harviston@gmail.com>
Copyright (c) 2014 Arve Knudsen <arve.knudsen@gmail.com>

BSD License
"""
def with_logger(cls):
    """Class decorator to add a logger to a class."""
    ...

